### ISSUE TITLE
Disconnected from peer: 127.0.0.1

### ISSUE THREAD

**Issue by IhorSavva** [osagga/bitcore-node-cash#3]
Did you up this node with bitcoin-cash? I installed the local bitcoin-abc node, but this bitcore node does not connect to the peer.
```
Connecting to p2p network.
[2018-06-29T10:12:07.237Z] info: Disconnected from peer: 127.0.0.1
[2018-06-29T10:12:12.191Z] info: Retrying connection to p2p network.
[2018-06-29T10:12:12.193Z] info: Disconnected from peer: 127.0.0.1
```

**Comment by osagga** [comment]
Make sure you're using the 'cash' branch of this repo. Also can you post the config files for Bitcore and bitcoin-abc?

**Comment by IhorSavva** [comment]
![image](https://user-images.githubusercontent.com/10389667/42089475-f0825fa4-7ba5-11e8-9591-15dff52a168f.png)


I use your default config files:
![image](https://user-images.githubusercontent.com/10389667/42089511-1d13cfee-7ba6-11e8-8fe3-e0581a7be90d.png)
![image](https://user-images.githubusercontent.com/10389667/42089531-320c0e5c-7ba6-11e8-9b9c-076e34e09735.png)

**Comment by osagga** [comment]
That's weird, are you sure that bitcoin-abc (or any other bitcoin cash node) is running independently before running this node?

**Comment by IhorSavva** [comment]
I solved the problem. 
In bitcoin.conf field: "maxconnections". 
due to the fact that the limit of connections was reached - the node did not allow to connect to itself

its work for me: maxconnections=50

**Comment by vladislavmamchich** [comment]
Did you up this node with bitcoin-cash? I installed the local bitcoin-abc node, but this bitcore node does not connect to the peer.
